#
#  Author: Hari Sekhon
#  Date: 2021-11-29 16:50:46 +0000 (Mon, 29 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    P r o m e t h e u s   N a m e s p a c e
# ============================================================================ #

---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    # "true" must be string, otherwise gets
    #  The request is invalid: patch: Invalid value: "map[metadata:map[labels:map[app.kubernetes.io/instance:<nil> goldilocks.fairwinds.com/enabled:true] resourceVersion:24479876]]": unrecognized type: string
    goldilocks.fairwinds.com/enabled: "true"
